// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZRbqYjq7o-1bU10aO_BJRnq9WmYZoP7M',
    appId: '1:121839034936:android:5f3f7484bcfaf217bd7ccd',
    messagingSenderId: '121839034936',
    projectId: 'spirootv2',
    databaseURL: 'https://spirootv2-default-rtdb.firebaseio.com',
    storageBucket: 'spirootv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0YRbgwcE2x3MLngpLQrDQAEkzAdw3agk',
    appId: '1:121839034936:ios:4af00b6e605e9509bd7ccd',
    messagingSenderId: '121839034936',
    projectId: 'spirootv2',
    databaseURL: 'https://spirootv2-default-rtdb.firebaseio.com',
    storageBucket: 'spirootv2.firebasestorage.app',
    iosClientId: '121839034936-02h7rv3qshotp9qrhers72mkmom42i99.apps.googleusercontent.com',
    iosBundleId: 'com.apptoic.spiroot1',
  );

}